AnjaliMIS/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using AnjaliMIS.Areas.HelpPage.ModelDescriptions;
using AnjaliMIS.Areas.HelpPage.Models;

namespace AnjaliMIS.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

AnjaliMIS/Controllers/LOC_CountryController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AnjaliMISRepository;
using AnjaliMISViewModal;

namespace AnjaliMIS.Controllers
{
    public class LOC_CountryController : Controller
    {
        public static LOC_CountryRepository _LOC_CountryRepository = new LOC_CountryRepository();
        public ActionResult Index()
        {
            //return View(l.GetAll().ToList());
            List<LOC_CountryViewModal> LOC_Country = _LOC_CountryRepository.getallCountry();
            return View(LOC_Country);
        }
        //// GET: tbInsertMobiles/Edit/5
        //public ActionResult Edit(long id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    LOC_Country country = _lOC_Country.GetById(id);
        //    if (country == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(country);
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "MobileID,MobileName,MobileIMEno,mobileprice,mobileManufacured,CreatedDate")] LOC_Country country)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        //db.Entry(_lOC_Country).State = EntityState.Modified;
        //        _lOC_Country.Add(country);
        //        return RedirectToAction("Index");
        //    }
        //    return View(country);
        //}

    }
}

AnjaliMIS/Controllers/LOC_StateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AnjaliMIS.Controllers
{
    public class LOC_StateController : Controller
    {
        //  private UnitOfWork unitOfWork = new UnitOfWork();
        //  private RepositoryBase<LOC_State> _lOC_State;

        //public LOC_StateController()
        //{
        //    _lOC_State = new RepositoryBase<LOC_State>(unitOfWork._context);
        //}
        //public ActionResult Index()
        //{
        //    IEnumerable<LOC_State> LOC_State = _lOC_State.GetAll();
        //    return View(LOC_State);
        //}

    }
}

AnjaliMIS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/assets/global/plugins/select2/select2.css")
    @Styles.Render("~/assets/global/plugins/datatables/extensions/Scroller/css/dataTables.scroller.min.css")
    @Styles.Render("~/assets/global/plugins/datatables/extensions/ColReorder/css/dataTables.colReorder.min.css")
    @Styles.Render("~/assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css")
    <style>
        input {
            /*width: 145px !important;*/
            font-size: 14px;
            font-weight: normal;
            color: #333;
            background-color: #fff;
            border: 1px solid #e5e5e5;
            box-shadow: none;
            transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
        }

        thead {
            font-weight: bold;
        }
    </style>
</head>
<body class="page-header-fixed page-quick-sidebar-over-content page-sidebar-closed-hide-logo page-container-bg-solid">
    <div class="page-header navbar navbar-fixed-top">
        <div class="page-header-inner">
            <div class="float-left">
                <h4 class="site-title " style="color:white !important; padding-left:10px; padding-top:3px ">
                    Anjali MIS
                </h4>
            </div>
            <div class="top-menu">
                <ul class="nav navbar-nav pull-right">
                    @*<li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="clearfix">
    </div>
    <div class="page-container">
        <div class="page-sidebar-wrapper">
            <div class="page-sidebar navbar-collapse collapse">
                <ul class="page-sidebar-menu " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
                    <li>@Html.ActionLink("Country", "index", "LOC_Country", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("State", "index", "LOC_State", new { area = "" }, null)</li>
                    @*<li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>*@
                </ul>
            </div>
        </div>
        <div class="page-content-wrapper">
            <div class="page-content">
                <div class="page-bar">
                    <ul class="page-breadcrumb">
                        <li>
                            <i class="fa fa-home"></i>
                            <a href="index.html">Home</a>
                            <i class="fa fa-angle-right"></i>
                        </li>
                        <li>
                            <a href="#">Dashboard</a>
                        </li>
                    </ul>
                    <div class="page-toolbar">

                    </div>
                </div>
                <h3 class="page-title">
                    @*Dashboard <small>reports & statistics</small>*@
                </h3>
                <div class="clearfix">
                </div>
                <div class="row">

                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
    @Scripts.Render("~/assets/global/plugins/jquery.min.js")
    @Scripts.Render("~/bundles/jquery")

    <script src="~/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    @*<script src="~/assets/admin/pages/scripts/table-advanced.js"></script>*@
    <script>
        jQuery(document).ready(function () {
            Metronic.init(); // init metronic core componets
            Layout.init(); // init layout
            QuickSidebar.init(); // init quick sidebar
            Demo.init(); // init demo features
            Index.init();
            Index.initDashboardDaterange();
            Index.initJQVMAP(); // init index page's custom scripts
            Index.initCalendar(); // init index page's custom scripts
            Index.initCharts(); // init index page's custom scripts
            Index.initChat();
            Index.initMiniCharts();
            Tasks.initDashboardWidget();
            Demo.init(); // init demo features
            //TableAdvanced.init();
        });
    </script>
    @RenderSection("scripts", required: false)
    @Scripts.Render("https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js")
    <script>

        $(document).ready(function () {
            $('#myTable').DataTable();
        });
    </script>

</body>
</html>